[pack]
name = "CHUJ - Create: Hardcore Ultimate Journey"
summary = "A hardcore Create-focused adventure pack for friends."
debug_version = "debug"

[dependencies]
minecraft = "1.20.1"
loader = "forge"
loader_version = "47.4.10"

[build]
slug = "chuj"
default_side = "both"
dist_dir = "dist"

# Create-related mods
[mods.create_addons]
mods = [
  #
  { url = "https://modrinth.com/project/LNytGWDc", side = "both", name = "Create" },

  # Main addons
  { url = "https://modrinth.com/project/ZzjhlDgM", side = "both", name = "Create: Steam 'n' Rails" },
  { url = "https://modrinth.com/project/ZM3tt6p1", side = "both", name = "Create: Diesel Generators" },
  { url = "https://modrinth.com/project/JWGBpFUP", side = "both", name = "Create: Enchantment Industry" },
  { url = "https://modrinth.com/project/z611fdf7", side = "both", name = "Create: Nuclear" },
  { url = "https://modrinth.com/project/WROfLLvn", side = "both", name = "Create: Trading Floor" },
  { url = "https://modrinth.com/project/btq68HMO", side = "both", name = "Create: Central Kitchen" },
  { url = "https://modrinth.com/project/4HnO3el1", side = "both", name = "Create: Food" },
  { url = "https://modrinth.com/project/bzzq7Auj", side = "both", name = "Create: Unbreakable Tools" },

  # QoL
  { url = "https://modrinth.com/project/L1RT5SJc", side = "both", name = "Create: Goggles" },
  { url = "https://modrinth.com/project/UbFnAd4l", side = "both", name = "Create: Jetpack" },
  { url = "https://modrinth.com/project/PRHeWeBs", side = "both", name = "Create: Utilities" },
  { url = "https://modrinth.com/project/wPQ6GgFE", side = "both", name = "Create: Power Loader" },
  { url = "https://modrinth.com/project/sH9tXU9f", side = "both", name = "Create: Liquid Fuel" },
  { url = "https://modrinth.com/project/Q4F90RHI", side = "both", name = "Create: Armor Trims" },
  { url = "https://modrinth.com/project/H6bJ8Ju4", side = "both", name = "Create: Tweaked Controllers" },
  { url = "https://modrinth.com/project/BBhCMftF", side = "both", name = "Create: Curios Jetpack & Backtank" },
  { url = "https://modrinth.com/project/QMGO17gm", side = "both", name = "Create: Factory Logistics" },
  { url = "https://modrinth.com/project/RYJzdkDr", side = "server", name = "Create: Threaded Trains" },

  # New receipes
  { url = "https://modrinth.com/project/KKlx33Ch", side = "both", name = "Create: Stones" },  
  { url = "https://modrinth.com/project/AqQzrKJo", side = "both", name = "Create: Renewable Brass" },  
  { url = "https://modrinth.com/project/Mn8ziD0c", side = "both", name = "Create: High Pressure" },
  { url = "https://modrinth.com/project/nGq1sdd2", side = "both", name = "Create: Renewable Netherite" },
  { url = "https://modrinth.com/project/ae2lDuIP", side = "both", name = "Create: Totem Factory" },  
  { url = "https://modrinth.com/project/qpDVQtGR", side = "both", name = "Create: Renewable Notch Apples" },
  { url = "https://modrinth.com/project/X9kjRZeX", side = "both", name = "Create: Oxidized" },

  # Decorations
  { url = "https://modrinth.com/project/UT2M39wf", side = "both", name = "Create: Copycats+" },
  { url = "https://modrinth.com/project/r4Knci2k", side = "both", name = "Create: Interiors" },
  { url = "https://modrinth.com/project/yGttHo06", side = "both", name = "Create: Sound of Steam" },
  { url = "https://modrinth.com/project/15fFZ3f4", side = "both", name = "Create: Framed" },
  { url = "https://modrinth.com/project/hSSqdyU1", side = "both", name = "Create: Encased" },
  { url = "https://modrinth.com/project/hddN8ksR", side = "both", name = "Create: Vibrant Vaults" },

  # [Let's Do] Vinery compatibility
  { url = "https://modrinth.com/project/BbP33Lgv", side = "both", name = "Create: [Let's Do] Vinery" }
]

[mods.mobs]
mods = [
  #
  { url = "https://modrinth.com/project/JiEhJ3WG", side = "both", name = "More Mob Variants" },

  #
  { url = "https://modrinth.com/project/qEYs2G9A", side = "both", name = "Golem Overhaul" },
  { url = "https://modrinth.com/project/MI1LWe93", side = "both", name = "Creeper Overhaul" },
  { url = "https://modrinth.com/project/Lq6ojcWv", side = "both", name = "Enderman Overhaul" },
  { url = "https://modrinth.com/project/Yd4wb5wZ", side = "both", name = "Critters and Companions" },
  { url = "https://modrinth.com/project/8YcE8y4T", side = "both", name = "Ribbits" },
  { url = "https://modrinth.com/project/gJKLGvbS", side = "both", name = "Ghost" },
  
  #
  { url = "https://modrinth.com/project/BOCJKD49", side = "both", name = "Friends & Foes" }
]

# Other gameplay/content mods
[mods.gameplay]
mods = [
  # Farmer's Delight
  { url = "https://modrinth.com/project/R2OftAxM", side = "both", name = "Farmer's Delight" },
  { url = "https://modrinth.com/project/yHN0njMr", side = "both", name = "End's Delight" },
  { url = "https://modrinth.com/project/O53VhQoZ", side = "both", name = "My Nether's Delight" },

  # [Let's Do] Vinery
  { url = "https://modrinth.com/project/1DWmBJVA", side = "both", name = "[Let's Do] Vinery" },
  
  # Vanilla blocks tweaks + Decorations
  { url = "https://modrinth.com/project/6iTJugQR", side = "both", name = "Amendments" },
  { url = "https://modrinth.com/project/fFEIiSDQ", side = "both", name = "Supplementaries" },
  { url = "https://modrinth.com/project/pJmCFF0p", side = "both", name = "Handcrafted" },

  # Map
  { url = "https://modrinth.com/project/1bokaNcj", side = "both", name = "Xaero's Minimap" },
  { url = "https://modrinth.com/project/NcUtCpym", side = "both", name = "Xaero's World Map" }
]

# Quality-of-life mods
[mods.qol]
mods = [
  { url = "https://modrinth.com/project/nvQzSEkH", side = "both", name = "Jade" },
  { url = "https://modrinth.com/project/EsAfCjCV", side = "both", name = "AppleSkin" },
  { url = "https://modrinth.com/project/u6dRKJwZ", side = "both", name = "Just Enough Items (JEI)" },
  { url = "https://modrinth.com/project/l6YH9Als", side = "both", name = "spark" },
  { url = "https://modrinth.com/project/8shC1gFX", side = "client", name = "BetterF3" },
  { url = "https://modrinth.com/project/idMHQ4n2", side = "client", name = "CustomSkinLoader" },
  { url = "https://modrinth.com/project/O7RBXm3n", side = "client", name = "Inventory Profiles Next" },
  { url = "https://modrinth.com/project/aC3cM3Vq", side = "client", name = "Mouse Tweaks" },
]

# Storage mods
[mods.storage]
mods = [
  { url = "https://modrinth.com/project/nmoqTijg", side = "both", name = "Sophisticated Core" },
  { url = "https://modrinth.com/project/hMlaZH8f", side = "both", name = "Sophisticated Storage" },
  { url = "https://modrinth.com/project/MJ0hdevs", side = "both", name = "Sophisticated Storage Create Integration" },
  { url = "https://modrinth.com/project/TyCTlI4b", side = "both", name = "Sophisticated Backpacks" },
  { url = "https://modrinth.com/project/s85zLEDe", side = "both", name = "Sophisticated Backpacks Create Integration" }
]

# Performance mods
[mods.performance]
mods = [
  { url = "https://modrinth.com/project/GchcoXML", side = "both", name = "Oculus" },
  { url = "https://modrinth.com/project/uXXizFIs", side = "both", name = "FerriteCore" },
  { url = "https://modrinth.com/project/NRjRiSSD", side = "both", name = "Memory Leak Fix" },
  { url = "https://modrinth.com/project/sk9rgfiA", side = "client", name = "Embeddium" },
  { url = "https://modrinth.com/project/NNAgCjsB", side = "client", name = "EntityCulling" },
  { url = "https://modrinth.com/project/5ZwdcRci", side = "client", name = "ImmediatelyFast" },
  { url = "https://modrinth.com/project/uCdwusMi", side = "client", name = "Distant Horizons" },
  { url = "https://modrinth.com/project/ndHYMY2K", side = "client", name = "Iris & Oculus Flywheel Compat" },
  { url = "https://modrinth.com/project/fALzjamp", side = "server", name = "Chunky" },
  { url = "https://modrinth.com/project/Wnxd13zP", side = "server", name = "Clumps" }
]

# Libraries
[mods.libraries]
mods = [
  { url = "https://modrinth.com/project/lhGA9TYQ", side = "both", name = "Architectury" },
  { url = "https://modrinth.com/project/40FYwb4z", side = "both", name = "Caelus API" },
  { url = "https://modrinth.com/project/9s6osm5g", side = "both", name = "Cloth Config v10 API" },
  { url = "https://modrinth.com/project/vvuO3ImH", side = "both", name = "Curios API" },
  { url = "https://modrinth.com/project/8BmcQJ2H", side = "both", name = "GeckoLib 4" },
  { url = "https://modrinth.com/project/ordsPcFz", side = "both", name = "Kotlin for Forge" },
  { url = "https://modrinth.com/project/Cg6Uc79H", side = "both", name = "Mantle" },
  { url = "https://modrinth.com/project/twkfQtEc", side = "both", name = "Moonlight Library" },
  { url = "https://modrinth.com/project/G1hIVOrD", side = "both", name = "Resourceful Lib" },
  { url = "https://modrinth.com/project/M1953qlQ", side = "both", name = "Resourcefulconfig" },
  { url = "https://modrinth.com/project/onSQdWhM", side = "both", name = "libIPN" },
  { url = "https://modrinth.com/project/Ua7DFN59", side = "both", name = "YUNG's API" },
  { url = "https://modrinth.com/project/XaDC71GB", side = "both", name = "Lithostitched" },
  { url = "https://modrinth.com/project/PuTjrq4T", side = "both", name = "Anvian's Lib" },
  { url = "https://modrinth.com/project/sk9knFPE", side = "both", name = "Rhino" },
  { url = "https://modrinth.com/project/umyGl7zF", side = "both", name = "KubeJS" },
]

# Resource packs
[resourcepacks.default]
packs = [
  #
  { url = "https://modrinth.com/project/PGGrfcvL", side = "client", name = "Better Lanterns" },
  { url = "https://modrinth.com/project/CZrLuVQo", side = "client", name = "Low Shield" },
  { url = "https://modrinth.com/project/uBBepXuH", side = "client", name = "Animated Items" },
  { url = "https://modrinth.com/project/6vhHOIKw", side = "client", name = "Enchant Icons" },
  { url = "https://modrinth.com/project/6udpuGCH", side = "client", name = "Even Better Enchants" },

  # Create themed
  { url = "https://modrinth.com/project/LkwIaJEE", side = "client", name = "Create Style Interface" },
  { url = "https://modrinth.com/project/M1lkKD8r", side = "client", name = "Create brass cursors" },
  { url = "https://modrinth.com/project/srJbhHkf", side = "client", name = "Create Style Sophisticated Backpacks" },
  { url = "https://modrinth.com/project/9MkP9t9t", side = "client", name = "Create Style Sophisticated Storages" }
]

# Shader packs
[shaderpacks.default]
packs = [
  { url = "https://modrinth.com/project/BkTdFBUU", side = "client", name = "Pastel Shaders" }
]
